console.log("Aplicação de teste, treinamento de Git")
console.log("Rodando o sistema de gerenciamento de jogos")
console.log("Aplicação em perfeita execução")
console.log("Teste: Linha 1")
console.log("Teste: Linha 2")
console.log("Teste: Linha 3")
